# Basic .travis.yml file for Travis CI service.

language: python
# Specify version's to test
python:
  #- "2.7"   # Need 3.2 or greater for mypy
  - "3.5"
  - "3.6"

# Setup anaconda
# Use conda for hard to build software like numpy and scipy
before_install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy
  - source activate test-environment

  # Install your program
  #- python setup.py install
  - pip install -r requirements.txt

# command to run tests
script:
  # - pytest --cov=examples.py --cov-report term-missing --durations 5
  - pytest --cov=. --cov-report term-missing
after_success:
  - coveralls
